ShellTest: main.o 
	g++ -std=c++11 -g main.o -o ShellTest

main.o: main.cpp
	g++ -std=c++11 -g -c main.cpp

clean:
	rm *.o ShellTest
	echo clean done                                                                                                                                                                                                                                                                                  
