ClockShell: main.o 
	g++ -std=c++11 -g main.o -o ClockShell

main.o: main.cpp
	g++ -std=c++11 -g -c main.cpp

clean:
	rm *.o ClockShell
	echo clean done                                                                                                                                                                                                                                                                                  
